// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_VrDrivingGame : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.vrDrivingGame_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.vrDrivingGame_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Boolean Pedal
        {
            get
            {
                return SteamVR_Actions.vrDrivingGame_Pedal;
            }
        }
        
        public virtual SteamVR_Action_Boolean Brake
        {
            get
            {
                return SteamVR_Actions.vrDrivingGame_Brake;
            }
        }
        
        public virtual SteamVR_Action_Boolean TurnLeft
        {
            get
            {
                return SteamVR_Actions.vrDrivingGame_TurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean TurnRight
        {
            get
            {
                return SteamVR_Actions.vrDrivingGame_TurnRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean ResetPosition
        {
            get
            {
                return SteamVR_Actions.vrDrivingGame_ResetPosition;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.vrDrivingGame_Haptic;
            }
        }
    }
}
